### ISSUE TITLE
Pull request with original

### ISSUE THREAD

**Issue by DamianSuess** [rromanovsky/clang-format-configurator#7]
@rromanovsky, do you mind creating a pull request with the original code repository? You did  A LOT of really nice contributions which many of us would like to see happen on the main website.

https://github.com/rromanovsky/clang-format-configurator

Thank you!

**Comment by rromanovsky** [comment]
Hey, @DamianSuess absolutely!
Sorry for long response I've sent the pull request: https://github.com/zed0/clang-format-configurator/pull/16
